"""initial

Revision ID: 7bb7e3f93b7a
Revises: 
Create Date: 2026-03-07 17:04:22.508668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb7e3f93b7a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparable_sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('sf', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Float(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=False),
    sa.Column('lot_sf', sa.Integer(), nullable=False),
    sa.Column('price_per_sf', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=False),
    sa.Column('depth_in', sa.Float(), nullable=False),
    sa.Column('bf_in', sa.Float(), nullable=False),
    sa.Column('area_in2', sa.Float(), nullable=False),
    sa.Column('ix_in4', sa.Float(), nullable=False),
    sa.Column('sx_in3', sa.Float(), nullable=False),
    sa.Column('zx_in3', sa.Float(), nullable=False),
    sa.Column('weight_plf', sa.Float(), nullable=False),
    sa.Column('fy_ksi', sa.Float(), nullable=False),
    sa.Column('e_ksi', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('designation')
    )
    op.create_table('zoning_districts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('max_height_ft', sa.Float(), nullable=False),
    sa.Column('front_setback_ft', sa.Float(), nullable=False),
    sa.Column('side_setback_ft', sa.Float(), nullable=False),
    sa.Column('rear_setback_ft', sa.Float(), nullable=False),
    sa.Column('far', sa.Float(), nullable=False),
    sa.Column('lot_coverage_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classification')
    )
    op.create_table('floor_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['floor_plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('model_type', sa.String(length=10), nullable=False),
    sa.Column('cost_per_sf', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=False),
    sa.Column('confidence_high', sa.Float(), nullable=False),
    sa.Column('feature_importance_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget_allocated', sa.Float(), nullable=False),
    sa.Column('budget_spent', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_selections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('floor_plan_id', sa.String(length=36), nullable=False),
    sa.Column('layer_number', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('waste_factor', sa.Float(), nullable=False),
    sa.Column('labor_rate', sa.Float(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structural_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('floor_plan_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('governing_combo_id', sa.String(length=10), nullable=True),
    sa.Column('max_moment', sa.Float(), nullable=False),
    sa.Column('max_shear', sa.Float(), nullable=False),
    sa.Column('max_deflection', sa.Float(), nullable=False),
    sa.Column('sci_score', sa.Float(), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structural_analyses')
    op.drop_table('material_selections')
    op.drop_table('schedules')
    op.drop_table('predictions')
    op.drop_table('floor_plans')
    op.drop_table('zoning_districts')
    op.drop_table('sections')
    op.drop_table('projects')
    op.drop_table('comparable_sales')
    # ### end Alembic commands ###
